import { WagmiConfig, createConfig } from "wagmi";
import { ConnectKitProvider, getDefaultConfig } from "connectkit";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const config = createConfig(	
  getDefaultConfig({
  // Required API Keys
  alchemyId: process.env.ALCHEMY_API_KEY, // or infuraId
  walletConnectProjectId: "demo",

  // Required
  appName: "You Create Web3 Dapp",

  // Optional
  appDescription: "Your App Description",
  appUrl: "https://family.co", // your app's url
  appIcon: "https://family.co/logo.png", // your app's logo,no bigger than 1024x1024px (max. 1MB)
})
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WagmiConfig config={config}>
        <ConnectKitProvider mode="dark">
          <body className={inter.className}>{children}</body>
        </ConnectKitProvider>
      </WagmiConfig>
    </html>
  );
};
