import { WagmiConfig, createConfig } from "wagmi";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const config = createConfig();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WagmiConfig config={config}>
        <body className={inter.className}>{children}</body>
      </WagmiConfig>
    </html>
  );
};
